# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
-
  id: "lbm"
  main: ./cmd/lbm
  binary: build/lbm
  env:
    - CGO_ENABLED=0
  flags:
    - -mod=readonly
    - -tags=netgo ledger
  ldflags:
    - -X github.com/line/lbm-sdk/version.Name=lbm
    - -X github.com/line/lbm-sdk/version.ServerName=lbm
    - -X github.com/line/lbm-sdk/version.Version={{ .Version }}
    - -X github.com/line/lbm-sdk/version.Commit={{ .FullCommit }}
    - -X "github.com/line/lbm-sdk/version.BuildTags=netgo,ledger"
archives:
-
  builds: ['lbm']
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  files:
    - LICENSE
    - docs/getting-started/*
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
