name: Build & Push
# Build & Push builds the lbm docker image on every tag push,
# and pushes the image to https://docker-registry.linecorp.com/link-network/v2/lbm
on:
  pull_request:
    branches:
      - main
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+" # Push events to matching v*, i.e. v1.0, v20.15.10
      - "v[0-9]+.[0-9]+.[0-9]+-*" # Push events to matching v*, i.e. v1.0-rc1, v20.15.10-alpha1

env:
  registry: docker.io
  repository: line/lbm
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Create a context for buildx
        run: docker context create buildx
      - name: Set up docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          endpoint: buildx
          config-inline: |
            [registry."docker.io"]
              mirrors = ["docker-hub-mirror.linecorp.com"]
      - name: login to the registry
        uses: docker/login-action@v2
        if: github.event_name != 'pull_request'
        with:
          registry: ${{env.registry}}
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: extract metadata for docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{env.registry}}/${{env.repository}}
          tags: |
            type=semver,pattern={{version}}
      - name: docker build
        uses: docker/build-push-action@v4
        with:
          push: ${{github.event_name != 'pull_request'}}
          build-args: ARCH=x86_64
          tags: ${{steps.meta.outputs.tags}}
          labels: ${{steps.meta.outputs.labels}}
          platforms: linux/amd64
