name: Check Make Format
# this workflow checks that go files is formated by `make format`
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  install-tools:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 1.18
      - name: Display go version
        run: go version
      - name: install tools
        run: |
          go install github.com/client9/misspell/cmd/misspell@v0.3.4 &&
          go install github.com/incu6us/goimports-reviser/v3@v3.4.5
      - uses: actions/cache@v3
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-misspell-v0.3.4-goimports-reviser-v3.4.5

  check-format:
    runs-on: ubuntu-latest
    needs: install-tools
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.18
      - name: Display go version
        run: go version
      - uses: actions/cache@v3
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-misspell-v0.3.4-goimports-reviser-v3.4.5
      - name: Make Format
        run: make format
      - name: Check Diff
        run: git diff --exit-code
