name: IBC E2E Test
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test-fnsa-fnsa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test finschia to finschia
        run: |
          rm -rf .git
          cd ibc_e2e
          make build-docker
          make test-fnsa-fnsa-in-docker

  test-fnsa-gaia:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test finschia to gaia
        run: |
          rm -rf .git
          cd ibc_e2e
          make build-docker
          make test-fnsa-gaia-in-docker
